### ISSUE TITLE
NPM version (version not found: html5shiv@3.7.2)

### ISSUE THREAD

**Issue by jontelm** [aFarkas/html5shiv#194]
version not found: html5shiv@3.7.2

"npm view express" gives multiple versions but html5shiv only give me one(3.7.3).

It had been good if it had a track record and a possibility to stay on one version when using npm.

Possible to keep old versions when adding new ones in npm?

**Comment by aFarkas** [comment]
I normally keep old version when adding new ones. This is one feature of versioning (getting older versions). However npm owner of old html5shiv versions was another non-official developer and he has removed those old versions.

Since version 3.7.3, I'm the owner now. But I can't bring back old versions, sorry.
